# Site settings
title: Flycheck
email: flycheck@lunaryorn.com
description: On the fly syntax checking for GNU Emacs
url: "http://flycheck.github.io"
github_username: flycheck

# Build settings
markdown: kramdown
