# Site settings
title: Flycheck
email: flycheck@lunaryorn.com
description: On the fly syntax checking for GNU Emacs
baseurl: ""
url: "http://flycheck.github.io"
github_username: flycheck

# Build settings
markdown: kramdown
timezone: UTC
encoding: utf-8

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
